apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "account-ledger.apiName" . }}
  namespace: {{ include "account-ledger.namespace" . }}
  labels:
    {{- include "account-ledger.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.api.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "account-ledger.apiName" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ include "account-ledger.apiName" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        {{- include "account-ledger.labels" . | nindent 8 }}
    spec:
      {{- with .Values.api.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: api
          image: "{{ .Values.api.image.repository }}:{{ .Values.api.image.tag }}"
          imagePullPolicy: {{ .Values.api.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.api.service.targetPort }}
          envFrom:
            - configMapRef:
                name: {{ include "account-ledger.configMapName" . }}
            - secretRef:
                name: {{ include "account-ledger.secretName" . }}
          readinessProbe:
            httpGet:
              path: {{ .Values.api.probes.path }}
              port: {{ .Values.api.service.targetPort }}
            initialDelaySeconds: {{ .Values.api.probes.readinessInitialDelaySeconds }}
            periodSeconds: {{ .Values.api.probes.readinessPeriodSeconds }}
          livenessProbe:
            httpGet:
              path: {{ .Values.api.probes.path }}
              port: {{ .Values.api.service.targetPort }}
            initialDelaySeconds: {{ .Values.api.probes.livenessInitialDelaySeconds }}
            periodSeconds: {{ .Values.api.probes.livenessPeriodSeconds }}
          resources:
            {{- toYaml .Values.api.resources | nindent 12 }}
