apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "account-ledger.configMapName" . }}
  namespace: {{ include "account-ledger.namespace" . }}
  labels:
    {{- include "account-ledger.labels" . | nindent 4 }}
data:
  ASPNETCORE_ENVIRONMENT: {{ .Values.api.env.ASPNETCORE_ENVIRONMENT | quote }}
  ASPNETCORE_URLS: {{ .Values.api.env.ASPNETCORE_URLS | quote }}
