{{- if .Values.namespace.create }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ include "account-ledger.namespace" . }}
  labels:
    {{- include "account-ledger.labels" . | nindent 4 }}
{{- end }}
